sudo: required
services:
  - docker

before_install:
  #  - docker build -t kamalpanhwar/react-test -f ./client/Dockerfile.dev ./client

script:
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # - docker build -t multi-server ./server
  # - docker tag multi-server:latest $DOCKER_ID/multi-server
  # - docker push $DOCKER_ID/multi-server 
  #
  # - docker build -t multi-client ./client
  # - docker images
  # - docker tag multi-client:latest $DOCKER_ID/multi-client
  # - docker push $DOCKER_ID/multi-client
  #
  # - docker build -t multi-worker:latest ./worker
  # - docker tag multi-worker:latest $DOCKER_ID/multi-worker
  # - docker push $DOCKER_ID/multi-worker
  #
  # - docker build -t multi-nginx:latest ./nginx
  # - docker tag multi-nginx:latest $DOCKER_ID/multi-nginx
  # - docker push $DOCKER_ID/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker-two
  env: Multi-docker-two-env
  bucket_name: "elasticbeanstalk-eu-west-2-693319392443"
  bucket_path: "docker-travis-ci"

  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

# after_success:
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#   - docker build -t kamalpanhwar/multi-client ./client
#   - docker images
#   - docker  push $DOCKER_USERNAME/multi-client
