sudo: required
services:
  - docker

before_install:
  #  - docker build -t kamalpanhwar/react-test -f ./client/Dockerfile.dev ./client

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t multi-client ./client
  - docker images
  - docker tag multi-client $DOCKER_USERNAME/multi-client
  - docker push $DOCKER_USERNAME/multi-client
  # - docker run -e CI=true kamalpanhwar/react-test npm test  --detectOpenHandles

# after_success:
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#   - docker build -t kamalpanhwar/multi-client ./client
#   - docker images
#   - docker  push $DOCKER_USERNAME/multi-client
